ci:
  autofix_commit_msg: "fix(pre-commit): auto fixes from pre-commit.com hooks\n\nfor more information, see https://pre-commit.ci"
  autofix_prs: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
#     - id: pretty-format-json
#       args:
#         - --autofix
#         - --indent 2
#         - --no-sort-keys
#         - --no-ensure-ascii
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
#     - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - feat
          - fix
          - docs
          - ci
          - chore
          - refactor
  - repo: https://github.com/golangci/golangci-lint
    rev: "ea3dbf1"
    hooks:
      - id: golangci-lint-full
        files: ^backend/
        entry: bash -c 'cd backend && golangci-lint run --fix'
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: "6451653"
    hooks:
      - id: go-build-repo-mod
      - id: go-mod-tidy
      - id: go-test-mod
        include: ^backend/
default_install_hook_types:
  - pre-commit
  - commit-msg
