services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8035:8080
    environment:
      HOMECALL_DB_HOST: db
      HOMECALL_DB_PASSWORD: supersecret
      HOMECALL_DB_PORT: 5432
      HOMECALL_AUTH_AUDIENCE: https://office-api.homecall.sidus.io
      HOMECALL_JITSI_APP_ID: ${HOMECALL_JITSI_APP_ID}
      HOMECALL_JITSI_KEY_ID: ${HOMECALL_JITSI_KEY_ID}
      HOMECALL_JITSI_KEY_FILE: jitsi_key.pem
    volumes:
      - ./jitsi_key.pem:/root/jitsi_key.pem
    depends_on:
        - db
    develop:
      watch:
        - path: backend
          action: rebuild
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: homecall
      POSTGRES_DB: homecall
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 8036:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8037:8080 # http://localhost:8037
volumes:
  pgdata:
